// auto generated by go tool dist

package runtime

const defaultGoroot = `/home/janson/projects/cloud/go1.5.4`
const theVersion = `go1.5.4`
const goexperiment = ``
const stackGuardMultiplier = 1
var buildVersion = theVersion
